name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
   external: true
services:
  mysql:
    image: saikumar718/mysql:v1.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
  backend:
    image: saikumar718/backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: saikumar718/frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"